### ISSUE TITLE
Given sample code not working on Next.js, type-script and React 16+ 

### ISSUE THREAD

**Issue by Dav157** [cedricdelpoux/react-google-map#16]
Server Error
TypeError: Cannot set property 'props' of undefined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages/test.tsx (79:31) @ eval

  77 | }
  78 |  
> 79 | export default GoogleMapLoader(Map, {
     |                               ^
  80 |   libraries: ["places"],
  81 |   key: MY_API_KEY,
  82 | })

Type error:
(alias) class GoogleMapLoader
(alias) namespace GoogleMapLoader
import GoogleMapLoader
Value of type 'typeof ReactGoogleMapsLoader' is not callable. Did you mean to include 'new'?

getting above error on type error

**Comment by cedricdelpoux** [comment]
It seems like `react-google-map` or `ReactGoogleMapsLoader` is not Server Side Rendering compatible. 
For now, you could test `typeof window !== "undefined"` and do not render your map if it's not the client.
But you also can open a PR to resolve the issue if you want to :)
