### ISSUE TITLE
package goes not work

### ISSUE THREAD

**Issue by codyc4321** [cedricdelpoux/react-google-map#3]
package does not work using es6

**Comment by cedricdelpoux** [comment]
What do you mean ? What kind of errors do you have ?

**Comment by stewest** [comment]
I get Module not found: Can't resolve 'react-google-maps-loader'

**Comment by cedricdelpoux** [comment]
`react-google-maps-loader` is an other package, you can found it [here](https://github.com/xuopled/react-google-maps-loader)

**Comment by stewest** [comment]
Great thanks, I've added it.
