### ISSUE TITLE
Fix React warnings

### ISSUE THREAD

**Issue by lfades** [cedricdelpoux/react-google-map#4]
React 16 will come out soon and some old deprecated code will be removed: https://github.com/facebook/react/issues/10294

in the case of this package, it should use `prop-types` from npm instead of importing propTypes from React:

"Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class"

**Comment by cedricdelpoux** [comment]
Hi, Thank you for reporting this. I will take care of this point soon. PR are welcome :)

**Comment by cedricdelpoux** [comment]
@Goluis I just release v3.1.0
